//
// dosbox_conf.cc — generate dosbox.conf and locate the dosbox binary.
//

#include "dosbox_conf.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <unistd.h>
#include <sys/stat.h>
#include <limits.h>
#include <libgen.h>

namespace dosemu {

namespace {

bool file_exists_x(const std::string &p) {
  struct stat st;
  return !p.empty() && stat(p.c_str(), &st) == 0 &&
         (st.st_mode & S_IXUSR) && S_ISREG(st.st_mode);
}

std::string which(const char *name) {
  const char *path = std::getenv("PATH");
  if (!path) return "";
  std::string p = path;
  size_t start = 0;
  while (start <= p.size()) {
    size_t sep = p.find(':', start);
    std::string dir = p.substr(start, sep - start);
    if (!dir.empty()) {
      std::string cand = dir + "/" + name;
      if (file_exists_x(cand)) return cand;
    }
    if (sep == std::string::npos) break;
    start = sep + 1;
  }
  return "";
}

// Make argv[0] → absolute path to the dir containing the dosemu binary.
std::string exe_dir(const char *argv0) {
  char buf[PATH_MAX];
  ssize_t n = readlink("/proc/self/exe", buf, sizeof(buf) - 1);
  if (n > 0) {
    buf[n] = 0;
    return std::string(dirname(buf));
  }
  // Fallback: use argv0
  if (argv0) {
    char tmp[PATH_MAX];
    std::strncpy(tmp, argv0, sizeof(tmp) - 1);
    tmp[sizeof(tmp) - 1] = 0;
    return std::string(dirname(tmp));
  }
  return ".";
}

// Quote a path for dosbox.conf (handles spaces; dosbox accepts double quotes).
std::string q(const std::string &s) { return "\"" + s + "\""; }

} // namespace

std::string locate_dosbox_binary(const Config &cfg, const char *argv0) {
  if (file_exists_x(cfg.dosbox_binary)) return cfg.dosbox_binary;
  if (const char *env = std::getenv("DOSEMU_DOSBOX")) {
    if (file_exists_x(env)) return env;
  }
  std::string here = exe_dir(argv0);
  // Dev layout: <dosemu>/build/dosemu -> <dosemu>/dosbox-staging/build/dosbox
  for (const char *rel : {
         "/../dosbox-staging/build/dosbox",
         "/../../dosbox-staging/build/dosbox",
         "/dosbox-staging/build/dosbox",
       }) {
    std::string cand = here + rel;
    if (file_exists_x(cand)) return cand;
  }
  if (std::string p = which("dosbox-staging"); !p.empty()) return p;
  if (std::string p = which("dosbox");         !p.empty()) return p;
  return "";
}

std::string write_dosbox_conf(const Config &cfg, const std::string &path) {
  std::string conf_path = path;
  if (conf_path.empty()) {
    char tmpl[] = "/tmp/dosemu-XXXXXX.conf";
    int fd = mkstemps(tmpl, 5);
    if (fd < 0) {
      std::perror("dosemu: mkstemps");
      return "";
    }
    close(fd);
    conf_path = tmpl;
  }

  FILE *f = std::fopen(conf_path.c_str(), "w");
  if (!f) {
    std::fprintf(stderr, "dosemu: cannot write %s: %s\n",
                 conf_path.c_str(), std::strerror(errno));
    return "";
  }

  std::fprintf(f, "# Generated by dosemu — do not edit by hand\n\n");

  std::fprintf(f, "[sdl]\n");
  if (cfg.headless) {
    // Dummy output: window still nominally exists but is not rendered/shown
    std::fprintf(f, "output = texture\n");
    std::fprintf(f, "fullscreen = false\n");
    // Headless is enforced by SDL_VIDEODRIVER=dummy in the child env.
  } else {
    std::fprintf(f, "fullscreen = false\n");
  }
  std::fprintf(f, "autolock = false\n\n");

  std::fprintf(f, "[dosbox]\n");
  std::fprintf(f, "machine = %s\n", cfg.machine.c_str());
  std::fprintf(f, "memsize = %d\n", cfg.memsize_mb);
  std::fprintf(f, "language = \n\n");

  std::fprintf(f, "[cpu]\n");
  std::fprintf(f, "core = %s\n", cfg.cpu_core.c_str());
  std::fprintf(f, "cputype = %s\n", cfg.cputype.c_str());
  std::fprintf(f, "cycles = auto\n\n");

  std::fprintf(f, "[mixer]\n");
  // Text-mode runs: mute mixer so no audio output is attempted.
  if (cfg.headless) std::fprintf(f, "nosound = true\n");
  std::fprintf(f, "\n");

  std::fprintf(f, "[autoexec]\n");

  // Mount drives. If cfg.drives is empty, default C: to cfg.chdir_path (or
  // the process CWD if that too is empty).
  if (cfg.drives.empty()) {
    std::string host = cfg.chdir_path;
    if (host.empty()) {
      char buf[PATH_MAX];
      if (getcwd(buf, sizeof(buf))) host = buf;
    }
    if (!host.empty())
      std::fprintf(f, "MOUNT C %s\n", q(host).c_str());
  } else {
    for (const auto &d : cfg.drives) {
      std::fprintf(f, "MOUNT %c %s\n", d.letter, q(d.host_path).c_str());
    }
  }

  // Switch to C: (first mounted drive), then run the program.
  char first_drive = cfg.drives.empty() ? 'C' : cfg.drives.front().letter;
  std::fprintf(f, "%c:\n", first_drive);

  if (!cfg.program.empty()) {
    // Build: "PROG.EXE" ARG1 ARG2 ...
    std::string cmdline = cfg.program;
    for (const auto &a : cfg.args) {
      cmdline += " ";
      cmdline += a;
    }
    std::fprintf(f, "%s\n", cmdline.c_str());
    std::fprintf(f, "exit\n");
  }

  std::fclose(f);
  return conf_path;
}

} // namespace dosemu
